### ISSUE TITLE
[Question] Why maxage is in millisecond... ?

### ISSUE THREAD

**Issue by frlinw** [koajs/send#103]
... when max-age is in second https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Cache-Control

**Comment by coderhaoxin** [comment]
@frlinw I think this answer is helpful.

https://github.com/pillarjs/cookies/issues/65#issuecomment-163776899

**Comment by Zappatta** [comment]
I know this issue is closed. And I know changing it will be a breaking change, and is not really possible. I don't expect you to change it. 

But I found this confusing as well.

Perhaps change documentation to emphasise the fact that it expects milliseconds?
