### ISSUE TITLE
Project Not Following Semver

### ISSUE THREAD

**Issue by shellscape** [koajs/send#106]
I just checked out the commits leading up to v5.0.0 (since there are no changelog nor release notes). There's nothing in those commits that would require a major version bump. Updating dependencies not directly used by exports to users doesn't constitute a semver major.

Please, please adhere to semver. Not doing so results in a time-suck for users.

**Comment by coderhaoxin** [comment]
this 5fadd484a5d7fc4abf380bd2fb636534e14b4a91 consider as a broken ~
