### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by tracker1** [koajs/send#108]
I was trying to make some optimizations, however the master branch tests are currently failing, not sure if I should be working against another branch, but I am uncertain if the expected/desired behavior is appropriate.

My intentions were as follows.

Optimizations: doing parallel fs.stat for path, path + '.gz' and path + '.br' instead of exists then stat calls.

Optimization: doing parallel fs.stat against all extensions using first match.

Option / Optimization: allow a caching `readFile` method option, that resolves to file content, or a readable stream.  (meant to be used with `read-cache` or similar).

**Comment by coderhaoxin** [comment]
@tracker1 all tests passed in my own pc :)

**Comment by tracker1** [comment]
@coderhaoxin what OS/platform are you running on?  I don't recall if I was at work (windows) or home (mac or linux) at the time I was trying to run the tests.

**Comment by coderhaoxin** [comment]
Travis CI build passed, feel free to submit a PR that shows how tests failed. :)
