### ISSUE TITLE
How to send two files?

### ISSUE THREAD

**Issue by vitorvr** [koajs/send#112]
Hi, I need to send 2 files (index.html and index.js).
Tried that:

`router.get('/', async (ctx) => {
    await send(ctx, ctx.path, { root: __dirname + '/public' });
  });`

But I got `Not found`

When I try to send `/public/index.html` works, but is missing index.js.

Thanks!

**Comment by coderhaoxin** [comment]
IMO, you need [koajs/static](https://github.com/koajs/static)
