### ISSUE TITLE
Support If-Modified-Since header

### ISSUE THREAD

**Issue by tracker1** [koajs/send#127]
Would be nice if this module would compare the date+time of the (not compressed) version of the file being requested, and if it's not newer than the `if-modified-since` header, then return a 304 response with an empty body.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since

Of course Etag support would also be nice.

**Comment by jonathanong** [comment]
https://github.com/koajs/conditional-get 

koa modules are meant to be simple and composable
