### ISSUE TITLE
Send with HTML file

### ISSUE THREAD

**Issue by robross0606** [koajs/send#137]
When I attemp to use `send()` with an .html file, the response comes back with a `status` of 200 but an empty `body`.

**Comment by zacanger** [comment]
Do you have a minimal reproduction? This tiny example works as expected:

```javascript
const Koa = require('koa')
const send = require('koa-send')

const app = new Koa()

app.use(async (ctx) => {
  await send(ctx, 'index.html')
})

app.listen(9999)
```

**Comment by robross0606** [comment]
This was from months ago.  I cannot recall how or where I was trying to use this.  I would just close the ticket.
