### ISSUE TITLE
Change send return type to promise

### ISSUE THREAD

**Issue by vladshcherbin** [koajs/send#139]
According to current version, return type of `send` function is [Function](https://github.com/koajs/send/blob/5.0.0/index.js#L33-L37). However it's an async function so I believe the return type is a promise.

I've checked previous versions (v3, v4) and in v3 `send` [was just a function](https://github.com/koajs/send/blob/3.0.0/index.js). Since v4 it was changed to an async function but types were not changed.

**Comment by zacanger** [comment]
Which types? If you're talking about TypeScript types, those are maintained in

**Comment by vladshcherbin** [comment]
JSDoc types in code. If you open first link in topic start message, they will be highlighted. This types are used by vscode when DefinitelyTyped types are not installed.

**Comment by vladshcherbin** [comment]
@zacanger thanks ❤️
