### ISSUE TITLE
acceptsEncodings throws under certain conditions

### ISSUE THREAD

**Issue by raphaelvalerio** [koajs/send#19]
Under certain (probably rare) circumstances, when `send` tries to run `this.acceptsEncodings()` it will throw the following error:

```bash
TypeError: this.acceptsEncodings is not a function
```

This only happens when `send` is being called, of course, from outside the Koa context, but there are circumstances where sometimes you have to run functions that aren't normal Koa middleware for BC reasons. In my case, this occurred when I called `send` in a custom callback from a `koa-passport` OAuth authentication strategy (Github, specifically), like follows:

```javascript
r.get('/auth/github/callback', function *() {
    let ctx = this;
    yield passport.authenticate('github', function *(err, user, info) {
      // ...
      yield send(ctx, returnPath, {root: path.resolve(__dirname, publicFolder)});
   }).call(this, next);
});
```

I have to assign `this` to `ctx` in the outer function because the context is lost during the authentication.

Because `send` is trying to call `acceptsEncodings` from `this` rather than the context that's passed in through the first argument, if the context of `this` is no longer Koa (as it will be in instances like the above) it will throw. I can use `.apply(ctx)` on `send` to fix the problem, but it's more streamlined (and, in my opinion, more fail-safe) to change line 48 of `index.js` from this:

```javascript
var encoding = this.acceptsEncodings('gzip', 'deflate', 'identity');
```

To this:

```javascript
var encoding = ctx.acceptsEncodings('gzip', 'deflate', 'identity');
```

Since this is the only call to `this` that I know if in the module, I would assume changing it to use `ctx` ensures that the module will work under any circumstance, providing the developer passes in the right context as the first argument (which is necessary anyway).

I forked and branched the fix which you can see at https://github.com/raphaelvalerio/send/tree/fix-acceptsEncodings. If you want I can run a PR with it.

**Comment by jonathanong** [comment]
i don't know what you're doing there. having a generator function as a callback is something you should never be doing

**Comment by raphaelvalerio** [comment]
@jonathanong You mean the generator callback as the second argument in `passport.authenticate` (`function *(err, user, info)`)? This is a requirement of `koa-passport`. It specifically throws if you do not use a generator function there.

Custom callback example from https://github.com/rkusa/koa-passport-example:

```javascript
public.post('/custom', function*(next) {
  var ctx = this
  yield* passport.authenticate('local', function*(err, user, info) {
    if (err) throw err
    if (user === false) {
      ctx.status = 401
      ctx.body = { success: false }
    } else {
      yield ctx.login(user)
      ctx.body = { success: true }
    }
  }).call(this, next)
})
```

If the callback is not a generator function then it throws with this error:

```bash
TypeError: Your custom authentication callback must be a Generator Function
```

There was an issue that discussed this as well: https://github.com/rkusa/koa-passport/issues/10

(Incidentally, I forgot to add the `call(this, next)` method in my original example and updated it accordingly)

**Comment by jonathanong** [comment]
terrible api. please reopen if you can provide a test case without any other modules!
