### ISSUE TITLE
How to send some multi files like combo?

### ISSUE THREAD

**Issue by lichenhao** [koajs/send#20]
RT~

**Comment by bitinn** [comment]
If you look at this line, this is not currently possible with `koa-send` alone.

https://github.com/koajs/send/blob/master/index.js#L86

but fortunately this is fairly easy with to implement with koa:

get the [query](http://koajs.com/#request-query) and read the files using [mz](https://github.com/normalize/mz) you need.

untested code:

```
var fs = require('mz/fs');

app.use(function *() {
  var combo = this.request.query.combo;
  var paths = combo.split(',');

  var files = yield paths.map(function(path) {
    return fs.readFile(path);
  });

  // concat or minify them as needed
});
```

or try https://github.com/tjwudi/koa-combo

**Comment by jonathanong** [comment]
are you asking if you want to send a multpart body? or a dynamic file server?

**Comment by lichenhao** [comment]
@bitinn  yeah, but this could not use the pipe as wish. I use the default request, response object instead.

**Comment by lichenhao** [comment]
@jonathanong  like CDN server, supported combo as well.

**Comment by bitinn** [comment]
@lichenhao you can use `fs.createReadStream` if you wish, but you have to roll your own code on this one. Also note that yield [a, b, c] run promise in parallel instead of in sequence.
