### ISSUE TITLE
Update mz dependency to 2.0

### ISSUE THREAD

**Issue by RamIdeas** [koajs/send#23]
Not the most pressing issue, but anytime I use npm my console gets polluted with an `npm WARN unmet dependency` message

`koa-send requires mz@'1.0.1 ' but will load ... version 2.0.0`

I've been using it without any problems. Is there a reason you're continuing to use the old version?

**Comment by jonathanong** [comment]
sorry for missing this... 92520465dd161a6a986454e0e28d942efcb1ec1f
