### ISSUE TITLE
Add examples for koa@2

### ISSUE THREAD

**Issue by tejasmanohar** [koajs/send#42]
3.x.x is promise-based

**Comment by coderhaoxin** [comment]
examples still work (koa@1)

**Comment by tejasmanohar** [comment]
but for koa@2?

**Comment by evenfrost** [comment]
I'm trying to use `send` with koa 2.0.0-alpha.3 and haven't managed to get it working with the new API. Is there any raw example? The following is not working for me:
```javascript
app.use(async function (ctx, next) {
  if (ctx.path === '/config.js') {
    await send(ctx, path.join(__dirname, 'config.js'));
  } else {
    await next();
  }
});
```
