### ISSUE TITLE
Does not throw when file does not exist

### ISSUE THREAD

**Issue by niieani** [koajs/send#43]
If a file does not exist there is no error. The promise resolves because and returns `undefined` on the `yield fs.stat` here:

``` js
    try {
      var stats = yield fs.stat(path);
      // nothing gets executed later on...
```

Not sure if that's a bug in `mz` or with the usage by koa-send.

**Comment by coderhaoxin** [comment]
See https://github.com/koajs/send/blob/master/index.js#L92

```js
      var notfound = ['ENOENT', 'ENAMETOOLONG', 'ENOTDIR'];
      if (~notfound.indexOf(err.code)) return;
```

You can check that by this

```js
var path = yield send(...);
if (!path) {
  // do something ...
}
```

**Comment by niieani** [comment]
I see, however it's not what I (and I presume most would have) expected. Not throwing on missing file lead me to waste an hour trying to find what the problem is. I think it's logical to have the default behavior throw an error when the file does not exist - on top of that this behavior is not documented. Especially that with throwing - it's as simple as try-catching the send for the end-user.

**Comment by coderhaoxin** [comment]
> I think it's logical to have the default behavior throw an error when the file does not exist

It's reasonable for me to respond `404`.
But it should be in the `README`. `PR` welcome

**Comment by niieani** [comment]
`404` is indeed reasonable, however I'll still argue the 404 should be coupled with an error thrown - since without an error thrown the 404 will not be logged unless the person manually watches for a null return value. All major file serving HTTP servers, including Apache and Nginx, throw an error when a file is not found and log it into an error.log file unless that feature is explicitly turned off. `koa-send`'s "quiet" behavior does not match that.

**Comment by tj** [comment]
Hmm it should still be logged, if you have a logger. If not I would say that's a logger bug, or it is not the top-most middleware. The absence of a response is a 404 implicitly, but having the error code etc sounds useful, throwing sounds reasonable to me

**Comment by niieani** [comment]
@tj Exactly. `404` happens regardless of `koa-send`, by default. Without an explicit throw it is hard to diagnose the problem and differentiate between an error coming from koa, the routing or in fact, an incorrect path / missing file.

**Comment by tj** [comment]
Haha yeah true, I find that with 404's all the time, hard to tell if it's a result of something missing in the db etc or just some screwed up route, little ambiguous. SGTM

**Comment by coderhaoxin** [comment]
@tj So, we need to do a broken change like this?

```js
if (~notfound.indexOf(err.code)) {
  err.status = 404;
  throw err;
}
```

**Comment by tj** [comment]
Yep! I think that should be good, can't think of any weird side-effects at the moment

**Comment by m-brian** [comment]
It doesn't seem to be the only problem with mz/fs.stat. Bluebird complains about every file served:
```
  Fri, 29 Jan 2016 06:16:36 GMT koa-send send "/public/thumbnails/2015-5/36.jpg" {"root":"."}
Warning: a promise was created in a handler but was not returned from it
    at Object.eval (eval at <anonymous> (./node_modules/thenify/index.js:30:15), <anonymous>:9:8)
    at ./node_modules/koa-send/index.js:77:28
    at next (native)
    at onFulfilled (./node_modules/co/index.js:65:19)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at next (./node_modules/co/index.js:100:51)
    at onFulfilled (./node_modules/co/index.js:69:7)
    at ./node_modules/co/index.js:54:5
    at co (./node_modules/co/index.js:50:10)
    at send (./node_modules/koa-send/index.js:36:10)
    at Object.<anonymous> (./app.js:138:23)
    at next (native)
    at onFulfilled (./node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:401:9)
```

**Comment by coderhaoxin** [comment]
@m-brian take a look at https://github.com/koajs/static/issues/62 https://github.com/koajs/send/issues/47

It's not the topic of this issue.

**Comment by tejasmanohar** [comment]
There are no actual negative effects here, and thus, it seems that there are no plans of updating `co` to return to avoid this warning. With that in mind, remember- Bluebird warnings are configurable :)

**Comment by yeliex** [comment]
may be it would be better to add a option: `allowedMethods` (throw error  instead of setting status and header,like `koa-router` )

**Comment by qwemaze** [comment]
Throwing an error if something went wrong is simply convenient and intuitive, why one should check a result if no file found?

It's purpose is to serve files and if requested path does not resolve it is wrong and it should throw.

**Comment by coderhaoxin** [comment]
#70

**Comment by coderhaoxin** [comment]
`v4.0.0` published !
