### ISSUE TITLE
Doesn't work with absolute paths

### ISSUE THREAD

**Issue by TMiguelT** [koajs/send#45]
Assuming there is a file named 'index.html' in the directory, accessing the server at localhost:3000 returns a 404 Not Found with the code below. Note that the file does exist and the path is correct, as demonstrated by the fs.statSync call.

```javascript
const app = require('koa')();
const send = require('koa-send');
const fs = require('fs');

const INDEX_FILE = `${__dirname}/index.html`;
// This string is an absolute path, e.g. in my case "/home/miguel/Programming/koa-send-test/index.html"

app.use(function*() {
	console.log(fs.statSync(INDEX_FILE)); //Returns a valid object
    yield send(this, INDEX_FILE); //Does nothing
});

app.listen(3000);
```

However if INDEX_FILE is set to a relative path, the code works fine and returns index.html when accessing localhost:3000
```javascript
const INDEX_FILE = `index.html`;
```

**Comment by cuttlas** [comment]
+1

**Comment by GreenGremlin** [comment]
This works if you set the root to '/'. But according to the documentation, that should not be necessary.

```
app.use(function*() {
    console.log(fs.statSync(INDEX_FILE)); //Returns a valid object
    yield send(this, INDEX_FILE, { root: '/' }); //Does nothing
});
```

**Comment by GreenGremlin** [comment]
On a second read of the documentation, I see setting root is necessary.

**Comment by GreenGremlin** [comment]
A better solution, for your example, is:

```
app.use(function*() {
    yield send(this, 'index.html');
});
// or
app.use(function*() {
    yield send(this, 'index.html', { root: __dirname });
});
```

**Comment by TMiguelT** [comment]
>Note that root is required, defaults to '' and will be resolved, removing the leading / to make the path relative

Okay I see that now. I guess what is confusing is that 'root' implies a path which everything will be relative to. Setting the root as '/' implies that the index file is literally in /index.html, the root of the entire filesystem. What actually happens, as it says here, is that the slash is removed (for some reason!) and then the path is made relative. What is the point of the slash then! 

This convention is particularly strange because if the slash indicates the current directory, how can you set the send root to /var/www without it looking in __dirname/var/www? 

I believe the most intuitive way of having koa-send work would be to use the root parameter as an absolute directory path (so / would refer to the actual filesystem root), but also having it defaults to the currently executed file's directory (e.g. `path.dirname(require.main.filename)`

**Comment by GreenGremlin** [comment]
It is that way to make sure developers don't inadvertently give access to the root file system. You can do what you're asking by setting the root option.

```
app.use(function*() {
    yield send(this, 'index.html', { root:'/var/www' });
});
```

**Comment by TMiguelT** [comment]
Ohhh I see. My first example was using an absolute path when it expects a path relative to the root, so we had to set root to '/' for it to make sense. 

Okay this behaviour makes a lot of sense. I think it's just the documentation that's confusing. I might get around to a PR if I get the time.
