### ISSUE TITLE
Update mz to get rid of native-or-bluebird deprecation

### ISSUE THREAD

**Issue by marionebl** [koajs/send#55]
When installing `koa-send` the following warning is produced:

```bash
npm WARN deprecated native-or-bluebird@1.2.0: please use 'any-promise' instead
```

This is caused by `mz@1.3.0` depending on `native-or-bluebird@1.2.0`:

```bash
❯ npm ls native-or-bluebird
mz@1.3.0
└── native-or-bluebird@1.2.0 
```

`mz@2.3` and up depend on the advertised replacement module `any-promise`

**Comment by coderhaoxin** [comment]
+1, will update soon.

**Comment by coderhaoxin** [comment]
0e2fe7613891fdbcc0382106e1965c3cac05f9f3

3.1.1

**Comment by marionebl** [comment]
:+1:
