### ISSUE TITLE
Should we allow customizing the cache-control header ?

### ISSUE THREAD

**Issue by Sinewyk** [koajs/send#56]
I want to add `must-revalidate` to the cache-control but I can't.

Read https://github.com/koajs/send/issues/39 but it doesn't help me if I want to set `Cache-Control` because it is overwritten here https://github.com/koajs/send/blob/0e2fe7613891fdbcc0382106e1965c3cac05f9f3/index.js#L100

Could this module allow passing a cacheControl option of some kind to just take control of the header entirely (in this case maxAge default and option is simply ignored) ?

**Comment by coderhaoxin** [comment]
Sounds reasonable.

Maybe we can add a option `setHeader`, just like https://github.com/expressjs/serve-static#setheaders

**Comment by Sinewyk** [comment]
[PR is open](https://github.com/koajs/send/pull/57), let me know what you think

**Comment by Sinewyk** [comment]
But I feel like maybe it needs a bigger/different README note. Because this should be used ONLY when we want to edit the three headers that are handled by send, which should be `Last-Modified`, `Cache-Control` and `Content-Length`.

**Comment by coderhaoxin** [comment]
> But I feel like maybe it needs a bigger/different README note

+1

**Comment by coderhaoxin** [comment]
closed by #57 697594751e82c0c83b87c21b9a0fef57053a0d52

**Comment by coderhaoxin** [comment]
697594751e82c0c83b87c21b9a0fef57053a0d52

**Comment by coderhaoxin** [comment]
697594751e82c0c83b87c21b9a0fef57053a0d52

**Comment by coderhaoxin** [comment]
3.2.0
