### ISSUE TITLE
Triggering a download in browser from Koa server?

### ISSUE THREAD

**Issue by zaynv** [koajs/send#60]
I'm trying to send a POST request from the client to the server. Upon receiving that POST request, the server should send the browser a file to be downloaded. I read the Koa docs, and it says that `this.attachment` should be used to prompt the client for download, but it doesn't seem to be doing anything.

Here is what I've tried:

**client.js**

```js
const { fetch } = window;

fetch('/download', { method: 'POST' });
```

**server.js**

```js
const Koa = require('koa');
const Router = require('koa-router');
const serve = require('koa-static');
const send = require('koa-send');

const app = new Koa();
const router = new Router();

router.post('/download', function * () {
  console.log('THIS IS RUNNING'); // This runs

  const path = `${__dirname}/blah.txt`;
  this.attachment('blah.txt');
  send(this, path);
});

app.use(serve(`${__dirname}/public`));
app.use(router.routes());
app.use(router.allowedMethods());

app.listen(3000);

```

However, nothing seems to happen, the file doesn't download. I've also tried changing `send(this, path);` to `this.body = send(this, path);` and that didn't do anything either (although it stopped the 404 error from coming since a `body` is now being sent as a response).

Am I understanding something wrong?

**Comment by coderhaoxin** [comment]
You are using `fetch` API, it's not koa's (server's) problem.

If you really want to download file by this way, there are some refs

http://stackoverflow.com/questions/32545632/how-can-i-download-a-file-using-window-fetch
http://stackoverflow.com/questions/19327749/javascript-blob-filename-without-link
