### ISSUE TITLE
Page type not set and path messed up

### ISSUE THREAD

**Issue by jeroenrinzema** [koajs/send#63]
Hi koa-send developers,
Currently am i working on a project and i am trying to implement koa-send.
https://github.com/projecthammer/hammer
But I am only running into a problem:

when i am trying to send a html file back to the client do i always have to define the root option:
https://github.com/projecthammer/hammer/blob/master/core/http/index.js#L52
If i am not doing this does koa-send mess up the path when it tries to resolve the path:
https://github.com/koajs/send/blob/master/index.js#L68
for some reason does it add root of the file again to the beginning of the path which causes that the path becomes invalid.
Is this a bug or do i always have to define the root option?

Also when the file is send back to the client is the 'type' header for some reason not set:
https://github.com/koajs/send/blob/master/index.js#L108
the type function nicely returns 'text/html' but for some reason is it not set in the response.

```
HTTP/1.1 404 Not Found
Content-Length: 138
Last-Modified: Fri, 14 Oct 2016 13:18:10 GMT
Cache-Control: max-age=0
Content-Type: application/json; charset=utf-8
Date: Fri, 14 Oct 2016 13:35:52 GMT
Connection: keep-alive
```

**Comment by jeroenrinzema** [comment]
I am sorry it was a bug in my own code. Could this issue be closed?

**Comment by dodekeract** [comment]
@jeroenrinzema You can close it, because you opened it. 🙂

**Comment by jeroenrinzema** [comment]
Haha sorry was searching for the button but didn't find it thnx! 😅
