### ISSUE TITLE
maxage is in miliseconds istead of seconds

### ISSUE THREAD

**Issue by seeden** [koajs/send#64]
you are using maxage / 1000

https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#max-age

**Comment by tj** [comment]
Unless my brain isn't functioning this is correct no? We document it as milliseconds, which is converted to seconds for max-age=. Milliseconds is sort of the defacto javascript unit

**Comment by seeden** [comment]
hi @tj 
I am sorry. I was reporting another issue because there was no information in documentation and I forgot to take a look in your documentation.
