### ISSUE TITLE
It's not enough just have max-age in header to cache the static files.

### ISSUE THREAD

**Issue by blade254353074** [koajs/send#71]
When I use iOS/OS X Safari to access static files (serve by koa-send).
The response headers has the `max-age=2628000`.
BUT when I press <kbd>CMD</kbd> + <kbd>R</kbd> or tap the iOS Safari refresh button...
Safari will set the request headers to `max-age=0`.
And then the cache is broken...

What if we set both of `max-age` and `expires`?
It will be better to add `last-modified` to koa-send.

**Comment by xeonselina** [comment]
and it should be an etag header too

**Comment by coderhaoxin** [comment]
@xeonselina [This module is for etag](https://github.com/koajs/etag)

@blade254353074 'Last-Modified' exists, see https://github.com/koajs/send/blob/master/index.js#L128

Also, you can use https://github.com/koajs/send#setheaders for other custom header :)

**Comment by blade254353074** [comment]
Thank you guys~
