### ISSUE TITLE
coverage test: use IstanbulJS(nyc) instead of legacy istanbul 0.4.0 to support async function instrumentation?

### ISSUE THREAD

**Issue by Gerhut** [koajs/send#78]
[IstanbulJS](https://istanbul.js.org/)

> Istanbul instruments your ES5 and ES2015+ JavaScript code with line counters, so that you can track how well your unit-tests exercise your codebase.
> The nyc command-line-client for Istanbul works well with most JavaScript testing frameworks: tap, mocha, AVA, etc.

**Comment by coderhaoxin** [comment]
Personally, I prefer `jest`. :)

For koa org, see https://github.com/koajs/koa/issues/703 ~

**Comment by Gerhut** [comment]
I see, just waiting for the decision of koa org.
