### ISSUE TITLE
Absolute path doesn't work

### ISSUE THREAD

**Issue by arshtepe** [koajs/send#80]
```
const send = require('koa-send');
send(ctx, "/asz/home/.../project/index.html");
//browser result ENOENT: no such file or directory, stat '/asz/home/.../project/asz/home/.../project/index.html'
```
Problem in this place https://github.com/koajs/send/blob/master/index.js#L45
parse( "/asz/home/.../project/index.html").root is equal to "/" and after substr path will be /asz/home/.../project/index.html

nodejs@v7.10.0
ubuntu 16.04

**Comment by coderhaoxin** [comment]
https://github.com/koajs/send#root-path
