### ISSUE TITLE
Trailing slash redirect

### ISSUE THREAD

**Issue by thepheer** [koajs/send#81]
There should be a way to redirect `/foo/bar` requests to `/foo/bar/` path to proper relative links handling.

Example: `<img src='hello.png'>` placed in `/foo/bar/index.html` won't load when you open `/foo/bar`.
The request goes to `/foo/hello.png` instead of `/foo/bar/hello.png`.

**Comment by niftylettuce** [comment]
see my comment here https://github.com/koajs/send/pull/125
