### ISSUE TITLE
It seems that it cannot handle 304.

### ISSUE THREAD

**Issue by lzszone** [koajs/send#93]
I set `Cache-Control` to `no-cache`, and set `Last-Modified` to a UTC time string in the `setHeaders`,
but the status code doesn't change in the browser, still 200.
I read the source and found that it did not handle the 304.

Do you need to provide this feature?
If so , I'd love to PR

**Comment by jonathanong** [comment]
use https://github.com/koajs/conditional-get and https://github.com/koajs/etag

**Comment by lzszone** [comment]
@jonathanong Get it, thanks
