### ISSUE TITLE
Can it support custom `Content-Type`?

### ISSUE THREAD

**Issue by mebtte** [koajs/send#96]
using `setHeaders: ctx => ctx.set('Content-Type', 'application/octet-stream')` is unsupported when i send `mp3` file, the response header is `audio/mpeg` still.

if i put
`if (setHeaders) setHeaders(ctx.res, path, stats)`
after
`ctx.type = type(path, encodingExt)`, it can works?

**Comment by coderhaoxin** [comment]
It's a BUG :) 
PR welcome !

**Comment by coderhaoxin** [comment]
Related commits https://github.com/koajs/send/commit/697594751e82c0c83b87c21b9a0fef57053a0d52

**Comment by coderhaoxin** [comment]
https://github.com/koajs/send/pull/101
